import os
from pathlib import Path
from dotenv import load_dotenv


# Load environment variables from the .env file
load_dotenv()


ASSETS = Path(__file__).parent / "assets"
LOG_FILE = ASSETS / "log" / "app.log"
TOPIC_FILE = ASSETS / "resources" / "topics.txt"

# Define the endpoint and API key for the News API, and the topic we want to search for news
NEWS_API_ENDOINT_EVERYTHING = "https://newsapi.org/v2/everything"
# NEWS_API_KEY = os.getenv("NEWS_API_KEY")
# SENDER_EMAIL = os.getenv("SENDER")
# SENDER_PASSWORD = os.getenv("PASSWORD")
DEFAULT_LANGUAGE = "en"

# Validation patterns
# topic consists of only word characters (letters, digits, and underscores)
TOPIC_PATTERN = r'^\w+$'
# language consists of exactly two lowercase letters
LANGUAGE_PATTERN = r'^[a-z]{2}$'
EMAIL_PATTERN = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

STOCKS = [
    "AAPL",  # Apple Inc.
    "MSFT",  # Microsoft Corporation
    "AMZN",  # Amazon.com Inc.
    "GOOGL",  # Alphabet Inc. (Google)
    "META",  # Meta Platforms, Inc. (formerly Facebook)
    "TSLA",  # Tesla, Inc.
    "BRK",  # Berkshire Hathaway Inc.
    "TCEHY",  # Tencent Holdings Limited
    "BABA",  # Alibaba Group Holding Limited
    "JNJ",  # Johnson & Johnson
    "JPM",  # JPMorgan Chase & Co.
    "V",  # Visa Inc.
    "MA",  # Mastercard Incorporated
    "WMT",  # Walmart Inc.
    "PG",  # Procter & Gamble Company
    "BAC",  # Bank of America Corporation
    "NSRGY",  # Nestle S.A.
    "005930.KS",  # Samsung Electronics Co., Ltd.
    "DIS",  # Walt Disney Company
    "HD",  # Home Depot, Inc.
    "INTC",  # Intel Corporation
    "TSM",  # Taiwan Semiconductor Manufacturing Company Limited (TSMC)
    "ADBE",  # Adobe Inc.
    "CSCO",  # Cisco Systems, Inc.
    "NKE",  # Nike, Inc.
    "PFE",  # Pfizer Inc.
    "UNH",  # UnitedHealth Group Incorporated
    "MCD",  # McDonald's Corporation
    "VZ",  # Verizon Communications Inc.
    "XOM",  # Exxon Mobil Corporation
    "TM",  # Toyota Motor Corporation
    "IBM",  # IBM (International Business Machines) Corporation
    "KO",  # Coca-Cola Company
    "GE",  # General Electric Company
    "NFLX",  # Netflix, Inc.
    "ABT",  # Abbott Laboratories
    "BA",  # Boeing Company
    "CAT",  # Caterpillar Inc.
    "CVX",  # Chevron Corporation
    "CMCSA",  # Comcast Corporation
    "DHR",  # Danaher Corporation
    "DELL",  # Dell Technologies Inc.
    "LLY",  # Eli Lilly and Company
    "F",  # Ford Motor Company
    "GM",  # General Motors Company
    "GS",  # Goldman Sachs Group, Inc.
    "HON",  # Honeywell International Inc.
    "JCI",  # Johnson Controls International plc
    "LMT",  # Lockheed Martin Corporation
    "MDT",  # Medtronic plc
    "MU",  # Micron Technology, Inc.
    "MS",  # Morgan Stanley
    "ORCL",  # Oracle Corporation
    "PEP",  # PepsiCo, Inc.
    "QCOM",  # Qualcomm Incorporated
    "RTX",  # Raytheon Technologies Corporation
    "CRM",  # Salesforce.com, Inc.
    "SLB",  # Schlumberger Limited
    "SIEGY",  # Siemens AG
    "TXN",  # Texas Instruments Incorporated
    "TTE",  # TotalEnergies SE
    "UPS",  # United Parcel Service, Inc. (UPS)
    "UNP",  # Union Pacific Corporation
    "UTX",  # United Technologies Corporation
    "WFC",  # Wells Fargo & Company
    "AZN",  # AstraZeneca plc
    "BBL",  # BHP Group
    "BMY",  # Bristol-Myers Squibb Company
    "CVS",  # CVS Health Corporation
    "DEO",  # Diageo plc
    "D",  # Dominion Energy, Inc.
    "DUK",  # Duke Energy Corporation
    "GSK",  # GlaxoSmithKline plc
    "MRK",  # Merck & Co., Inc.
    "NEE",  # NextEra Energy, Inc.
    "NVS",  # Novartis AG
    "NVDA",  # NVIDIA Corporation
    "OXY",  # Occidental Petroleum Corporation
    "PM",  # Philip Morris International Inc.
    "RIO",  # Rio Tinto Group
    "RDS",  # Royal Dutch Shell plc
    "SNY",  # Sanofi
    "ARAMCO",  # Saudi Aramco
    "SONY"  # Sony Group Corporation
]


NEWS_TOPICS = [
    'politics', 'sports', 'technology', 'health', 'entertainment',
    'business', 'science', 'world', 'travel', 'environment', 'education',
    'economy', 'weather', 'crime', 'culture', 'food', 'art', 'music',
    'movies', 'television', 'fashion', 'religion', 'history', 'space',
    'finance', 'aviation', 'automobile', 'energy', 'fitness', 'gaming',
    'celebrities', 'literature', 'journalism', 'law', 'philosophy',
    'psychology', 'socialmedia', 'internet', 'cybersecurity', 'gadgets',
    'startups', 'innovation', 'sustainability', 'equality', 'humanrights',
    'mentalhealth', 'wildlife', 'architecture', 'design', 'cryptocurrency',
    'blockchain', 'virtualreality', 'augmentedreality', 'biotechnology',
    'nanotechnology', 'robotics', 'drones', 'agriculture', 'forestry',
    'fisheries', 'conservation', 'climatechange', 'pollution', 'oceans',
    'volcanoes', 'earthquakes', 'disasters', 'refugees', 'immigration',
    'diplomacy', 'terrorism', 'conflict', 'peace', 'internationalrelations',
    'unitednations', 'government', 'elections', 'democracy', 'authoritarianism',
    'populism', 'freedomofspeech', 'privacy', 'surveillance', 'censorship',
    'protests', 'activism', 'civilrights', 'racialjustice', 'genderequality',
    'sexualorientation', 'genderidentity', 'families', 'parenting', 'educationreform',
    'discovery', 'celebration', 'artificialintelligence', 'inspiration',
    'celebration', 'innovation', 'creativity', 'discovery', 'exploration',
    'invention', 'adventure', 'community', 'optimism', 'change', 'revolution',
    'leadership', 'progress', 'challenge', 'opportunity', 'equality', 'diversity',
    'inclusion', 'harmony', 'collaboration', 'achievement', 'victory', 'resilience',
    'survival', 'recovery', 'hope', 'optimism', 'perseverance', 'compassion',
    'kindness', 'empathy', 'happiness', 'inspiration', 'motivation', 'empowerment',
    'success', 'ambition', 'dreams', 'goals', 'future', 'opportunity', 'growth',
    'prosperity', 'education', 'learning', 'knowledge', 'wisdom', 'creativity',
    'innovation', 'imagination', 'science', 'technology', 'progress', 'change',
    'adaptation', 'evolution', 'environment', 'sustainability', 'conservation',
    'climate', 'weather', 'nature', 'wildlife', 'ecosystem', 'ocean', 'forest',
    'planet', 'earth', 'discovery', 'exploration', 'space', 'universe', 'cosmos',
    'healthcare', 'medicine', 'wellness', 'nutrition', 'fitness', 'mentalhealth',
    'therapy', 'wellbeing', 'exercise', 'yoga', 'meditation', 'mindfulness',
    'stress', 'anxiety', 'depression', 'therapy', 'counseling', 'selfcare',
    'holistic', 'diet', 'weightloss', 'exercise', 'cardio', 'strengthtraining',
    'flexibility', 'endurance', 'physicaltherapy', 'rehabilitation', 'recovery',
    'healthyliving', 'lifestyle', 'wellness', 'prevention', 'screening',
    'diagnosis', 'treatment', 'management', 'recovery', 'surgery', 'medication',
    'pharmaceuticals', 'biotechnology', 'research', 'clinicaltrials', 'innovation',
    'breakthrough', 'progress', 'discovery', 'treatment', 'cure', 'vaccine',
    'publichealth', 'globalhealth', 'epidemiology', 'pandemic', 'outbreak',
    'infectiousdisease', 'immunology', 'virology', 'bacteriology', 'pathology',
    'genetics', 'bioinformatics', 'precisionmedicine', 'personalizedmedicine',
    'healthinformatics', 'telemedicine', 'digitalhealth', 'mhealth', 'ehealth',
    'telehealth', 'wearables', 'healthtech', 'medicaldevices', 'biotech',
    'pharmaceutical', 'healthcareindustry', 'healthcarepolicy', 'healthcareeconomics',
    'healthcaremanagement', 'healthcareadministration', 'healthcarereform',
    'universalhealthcare', 'healthinsurance', 'healthcaresystem', 'hospitals',
    'clinics', 'medicalcenters', 'urgentcare', 'emergencyroom', 'primarycare',
    'specialtycare', 'longtermcare', 'nursinghomes', 'assistedliving',
    'homehealthcare', 'hospicecare', 'mentalhealthcare', 'behavioralhealth',
    'addiction', 'substanceabuse', 'mentalillness', 'psychiatriccare',
    'therapy', 'counseling', 'rehabilitation', 'recovery', 'mentalhealthawareness',
    'suicideprevention', 'crisisintervention', 'emotionalwellness', 'mindfulness',
    'selfcare', 'wellbeing', 'supportgroups', 'peerupport', 'communitysupport',
    'advocacy', 'mentalhealthresources', 'awareness', 'education', 'stigma',
    'breakingthestigma', 'endthestigma', 'campaigns', 'initiatives', 'events',
    'activism', 'socialjustice', 'equality', 'civilrights', 'humanrights',
    'diversity', 'inclusion', 'intersectionality', 'empowerment', 'advocacy',
    'activism', 'solidarity', 'breakingthestigma', 'endthestigma', 'campaigns', 'initiatives', 'events',
    'activism', 'socialjustice', 'equality', 'civilrights', 'humanrights',
    'diversity', 'inclusion', 'intersectionality', 'empowerment', 'advocacy',
    'activism', 'solidarity', 'community', 'grassroots', 'mobilization',
    'awareness', 'education', 'justice', 'freedom', 'peace', 'unity',
    'changemakers', 'leadership', 'progress', 'transformation', 'hope',
    'inspiration', 'motivation', 'resilience', 'perseverance', 'compassion',
    'empathy', 'kindness', 'fairness', 'tolerance', 'respect', 'dignity',
    'integrity', 'honor', 'pride', 'courage', 'bravery', 'heroism',
    'sacrifice', 'generosity', 'gratitude', 'forgiveness', 'reconciliation',
    'trust', 'cooperation', 'collaboration', 'partnership', 'solidarity',
    'friendship', 'love', 'family', 'community', 'belonging', 'togetherness',
    'companionship', 'support', 'affection', 'care', 'compassion',
    'understanding', 'empathy', 'sympathy', 'encouragement', 'motivation',
    'inspiration', 'positivevibes', 'goodvibes', 'positivity', 'optimism',
    'hope', 'happiness', 'joy', 'gratitude', 'appreciation', 'contentment',
    'fulfillment', 'wellbeing', 'health', 'vitality', 'energy', 'enthusiasm',
    'passion', 'creativity', 'imagination', 'innovation', 'ambition', 'drive',
    'determination', 'persistence', 'resilience', 'strength', 'courage',
    'bravery', 'confidence', 'selfesteem', 'selfconfidence', 'selfcare',
    'selflove', 'selfcompassion', 'selfacceptance', 'selfawareness', 'mindfulness',
    'meditation', 'reflection', 'introspection', 'growth', 'development',
    'learning', 'education', 'knowledge', 'wisdom', 'insight', 'awareness',
    'consciousness', 'awakening', 'enlightenment', 'transformation', 'change',
    'adaptation', 'evolution', 'progress', 'success', 'achievement', 'victory',
    'triumph', 'accomplishment', 'fulfillment', 'satisfaction', 'contentment',
    'gratification', 'honor', 'recognition', 'appreciation', 'respect',
    'admiration', 'celebration', 'commemoration', 'tribute', 'memorial',
    'remembrance', 'legacy', 'heritage', 'tradition', 'culture', 'identity',
    'belonging', 'roots', 'ancestry', 'lineage', 'legacy', 'heritage', 'tradition',
    'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage',
    'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots',
    'ancestry', 'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture', 'identity',
    'belonging', 'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage', 'tradition',
    'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage',
    'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots',
    'ancestry', 'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture', 'identity',
    'belonging', 'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage', 'tradition',
    'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage',
    'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots',
    'ancestry', 'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture', 'identity',
    'belonging', 'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage', 'tradition',
    'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage',
    'heritage', 'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'identity', 'belonging',
    'roots', 'ancestry', 'lineage', 'heritage', 'tradition', 'culture',
    'identity', 'belonging', 'roots', 'ancestry', 'lineage', 'heritage',
    'tradition', 'culture', 'identity', 'belonging', 'roots', 'ancestry',
    'lineage', 'heritage', 'tradition', 'culture', 'sex', 'sexual']


top_100_companies = [
    "Apple",
    "Microsoft",
    "Amazon",
    "Alphabet",
    "Meta Platforms",
    "Tesla",
    "Berkshire Hathaway",
    "Tencent Holdings",
    "Alibaba Group",
    "Johnson & Johnson",
    "JPMorgan Chase",
    "Visa",
    "Mastercard",
    "Walmart",
    "Procter & Gamble",
    "Bank of America",
    "Nestle",
    "Samsung Electronics",
    "Walt Disney",
    "Home Depot",
    "Intel",
    "Taiwan Semiconductor Manufacturing Company",
    "Adobe",
    "Cisco Systems",
    "Nike",
    "Pfizer",
    "UnitedHealth Group",
    "McDonald's",
    "Verizon Communications",
    "Exxon Mobil",
    "Toyota Motor",
    "IBM",
    "Coca-Cola",
    "General Electric",
    "Netflix",
    "Abbott Laboratories",
    "Boeing",
    "Caterpillar",
    "Chevron",
    "Comcast",
    "Danaher",
    "Dell Technologies",
    "Eli Lilly",
    "Ford Motor",
    "General Motors",
    "Goldman Sachs Group",
    "Honeywell International",
    "Johnson Controls International",
    "Lockheed Martin",
    "Medtronic",
    "Micron Technology",
    "Morgan Stanley",
    "Oracle",
    "PepsiCo",
    "Qualcomm",
    "Raytheon Technologies",
    "Salesforce",
    "Schlumberger",
    "Siemens",
    "Texas Instruments",
    "TotalEnergies",
    "United Parcel Service",
    "Union Pacific",
    "United Technologies",
    "Wells Fargo",
    "AstraZeneca",
    "BHP Group",
    "Bristol-Myers Squibb",
    "CVS Health",
    "Diageo",
    "Dominion Energy",
    "Duke Energy",
    "GlaxoSmithKline",
    "Merck",
    "NextEra Energy",
    "Novartis",
    "NVIDIA",
    "Occidental Petroleum",
    "Philip Morris International",
    "Rio Tinto",
    "Royal Dutch Shell",
    "Sanofi",
    "Saudi Aramco",
    "Sony Group"
]


top_100_cars = [
    "Toyota",
    "Volkswagen",
    "Ford",
    "Honda",
    "General Motors",
    "Nissan",
    "Hyundai",
    "Mercedes-Benz",
    "BMW",
    "Tesla",
    "Renault",
    "Audi",
    "Fiat Chrysler Automobiles",
    "Volvo",
    "Mitsubishi",
    "Kia",
    "Peugeot",
    "Jaguar Land Rover",
    "Subaru",
    "Porsche",
    "Mazda",
    "Geely",
    "Suzuki",
    "Changan Automobile",
    "Daimler",
    "BYD",
    "Tata Motors",
    "Mahindra & Mahindra",
    "Isuzu",
    "Ferrari",
    "Great Wall Motors",
    "Chery",
    "Proton",
    "BAIC Group",
    "SAIC Motor",
    "NIO",
    "Haval",
    "Dongfeng Motor",
    "Chery",
    "Brilliance Auto",
    "Foton",
    "MG Motor",
    "BYD Auto",
    "Dacia",
    "Lexus",
    "Bentley",
    "Lada",
    "Mini",
    "SEAT",
    "Smart",
    "Daihatsu",
    "Cadillac",
    "Jeep",
    "Lincoln",
    "Acura",
    "Land Rover",
    "Alfa Romeo",
    "Skoda",
    "Citroën",
    "Dodge",
    "Infiniti",
    "GMC",
    "Buick",
    "Lamborghini",
    "Ram Trucks",
    "Subaru",
    "Jaguar",
    "Maserati",
    "Ferrari",
    "Pagani",
    "Lotus",
    "McLaren",
    "Koenigsegg",
    "Rolls-Royce",
    "Bugatti",
    "Alpina",
    "Aston Martin",
    "Spyker",
    "Rimac Automobili",
    "DeLorean Motor Company",
    "Lucid Motors",
    "Rivian",
    "Faraday Future",
    "Nikola Corporation",
    "Lordstown Motors",
    "Canoo",
    "Fisker Inc.",
    "Bollinger Motors",
    "Rivian",
    "Karma Automotive",
    "Lucid Motors",
    "Faraday Future",
    "Polestar",
    "Arrival",
    "Elio Motors",
    "Arcimoto",
    "Local Motors"
]

top_100_animals = [
    "lion",
    "tiger",
    "elephant",
    "giraffe",
    "cheetah",
    "leopard",
    "rhinoceros",
    "hippopotamus",
    "zebra",
    "gorilla",
    "orangutan",
    "chimpanzee",
    "baboon",
    "monkey",
    "koala",
    "kangaroo",
    "wallaby",
    "wombat",
    "platypus",
    "echidna",
    "crocodile",
    "alligator",
    "caiman",
    "python",
    "boa",
    "anaconda",
    "komodo dragon",
    "iguana",
    "chameleon",
    "gecko",
    "frog",
    "toad",
    "salamander",
    "newt",
    "axolotl",
    "tortoise",
    "turtle",
    "cobra",
    "rattlesnake",
    "viper",
    "mamba",
    "king cobra",
    "python",
    "anaconda",
    "boar",
    "wild boar",
    "warthog",
    "hippopotamus",
    "rhinoceros",
    "elephant",
    "giraffe",
    "zebra",
    "kangaroo",
    "wallaby",
    "koala",
    "wombat",
    "platypus",
    "echidna",
    "kookaburra",
    "emu",
    "cassowary",
    "ostrich",
    "hawk",
    "eagle",
    "falcon",
    "vulture",
    "owl",
    "hawk",
    "eagle",
    "falcon",
    "vulture",
    "owl",
    "parrot",
    "cockatoo",
    "macaw",
    "lorikeet",
    "budgerigar",
    "cockatiel",
    "finch",
    "canary",
    "sparrow",
    "starling",
    "pigeon",
    "dove",
    "seagull",
    "albatross",
    "pelican",
    "flamingo",
    "stork",
    "heron",
    "egret",
    "ibis",
    "spoonbill",
    "duck",
    "goose",
    "swan",
    "penguin",
    "seal",
    "sea lion",
    "walrus",
    "otter",
    "beaver",
    "mongoose",
    "meerkat",
    "prairie dog",
    "squirrel",
    "chipmunk",
    "hare",
    "rabbit",
    "cottontail",
    "jackrabbit",
    "pika",
    "mole",
    "shrew",
    "hedgehog",
    "porcupine",
    "armadillo",
    "anteater",
    "sloth",
    "bat",
    "flying fox",
    "lemur",
    "tarsier",
    "loris",
    "slow loris",
    "bushbaby",
    "galago",
    "ring-tailed lemur",
    "ruffed lemur",
    "indri",
    "sifaka",
    "lemur",
    "tarsier",
    "loris",
    "slow loris",
    "bushbaby",
    "galago",
    "ring-tailed lemur",
    "ruffed lemur",
    "indri",
    "sifaka",
    "lemur",
    "tarsier",
    "loris",
    "slow loris",
    "bushbaby",
    "galago",
    "ring-tailed lemur",
    "ruffed lemur",
    "indri",
    "sifaka"
]

top_100_fruits = [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Watermelon",
    "Mango",
    "Pineapple",
    "Peach",
    "Pear",
    "Cherry",
    "Blueberry",
    "Raspberry",
    "Kiwi",
    "Cantaloupe",
    "Plum",
    "Lemon",
    "Lime",
    "Apricot",
    "Grapefruit",
    "Avocado",
    "Coconut",
    "Pomegranate",
    "Papaya",
    "Fig",
    "Cranberry",
    "Blackberry",
    "Lychee",
    "Passion Fruit",
    "Tangerine",
    "Nectarine",
    "Guava",
    "Date",
    "Kiwi",
    "Dragonfruit",
    "Starfruit",
    "Persimmon",
    "Jackfruit",
    "Durian",
    "Rambutan",
    "Mangosteen",
    "Mulberry",
    "Clementine",
    "Cactus Pear",
    "Loquat",
    "Feijoa",
    "Ackee",
    "Plantain",
    "Kumquat",
    "Longan",
    "Cherimoya",
    "Quince",
    "Passionfruit",
    "Tamarillo",
    "Ugli Fruit",
    "Pomelo",
    "Soursop",
    "Feijoa",
    "Sapodilla",
    "Miracle Fruit",
    "Jabuticaba",
    "Persimmon",
    "Pawpaw",
    "Feijoa",
    "Mamey Sapote",
    "Rambutan",
    "Physalis",
    "Cherimoya",
    "Monstera Deliciosa",
    "Kiwano",
    "Durian",
    "Star Apple",
    "Surinam Cherry",
    "Ackee",
    "Passion Fruit",
    "Star Gooseberry",
    "Pitaya",
    "Breadfruit",
    "Mangosteen",
    "Cupuacu",
    "Jujube",
    "Pepino",
    "Prickly Pear",
    "Poha Berry",
    "Bael Fruit",
    "Cempedak",
    "Pulasan",
    "Bilimbi",
    "Indian Fig",
    "Cranberry",
    "Blackcurrant",
    "Chokeberry",
    "Cloudberry",
    "Gooseberry",
    "Loganberry",
    "Salmonberry",
    "Açaí Berry",
    "Barberry",
    "Black Raspberry",
    "Boysenberry",
    "Buffaloberry",
    "Cape Gooseberry",
    "Cloud Berry",
    "Currant",
    "Elderberry",
    "Goji Berry",
    "Huckleberry",
    "Juniper Berry",
    "Lingonberry",
    "Mulberry",
    "Nannyberry",
    "Sea Buckthorn",
    "Snowberry",
    "Saskatoon Berry",
    "Serviceberry"
]

top_100_vegetables = [
    "Spinach",
    "Kale",
    "Broccoli",
    "Carrot",
    "Tomato",
    "Bell Pepper",
    "Cabbage",
    "Lettuce",
    "Cucumber",
    "Zucchini",
    "Eggplant",
    "Brussels Sprouts",
    "Asparagus",
    "Green Beans",
    "Peas",
    "Corn",
    "Artichoke",
    "Celery",
    "Onion",
    "Garlic",
    "Potato",
    "Sweet Potato",
    "Beetroot",
    "Radish",
    "Turnip",
    "Pumpkin",
    "Squash",
    "Mushroom",
    "Okra",
    "Fennel",
    "Leek",
    "Chili Pepper",
    "Jalapeno",
    "Cauliflower",
    "Radish",
    "Chard",
    "Romaine Lettuce",
    "Arugula",
    "Watercress",
    "Bok Choy",
    "Endive",
    "Radicchio",
    "Scallion",
    "Shallot",
    "Green Onion",
    "Garlic Scapes",
    "Kohlrabi",
    "Parsnip",
    "Rutabaga",
    "Chicory",
    "Cress",
    "Water Spinach",
    "Sorrel",
    "Broccolini",
    "Mustard Greens",
    "Collard Greens",
    "Swiss Chard",
    "Snow Peas",
    "Snap Peas",
    "String Beans",
    "Edamame",
    "Lima Beans",
    "Black Beans",
    "Kidney Beans",
    "Pinto Beans",
    "Chickpeas",
    "Green Peas",
    "English Peas",
    "Split Peas",
    "Yellow Squash",
    "Acorn Squash",
    "Butternut Squash",
    "Spaghetti Squash",
    "Hubbard Squash",
    "Delicata Squash",
    "Gem Squash",
    "Pattypan Squash",
    "Crookneck Squash",
    "Yellow Zucchini",
    "Green Zucchini",
    "Button Mushroom",
    "Portobello Mushroom",
    "Shiitake Mushroom",
    "Cremini Mushroom",
    "Oyster Mushroom",
    "Chanterelle Mushroom",
    "Enoki Mushroom",
    "Maitake Mushroom",
    "Morel Mushroom",
    "Truffle Mushroom",
    "Porcini Mushroom",
    "Lion's Mane Mushroom",
    "King Oyster Mushroom",
    "Beech Mushroom",
    "Wood Ear Mushroom",
    "Tomatillo",
    "Fennel Bulb",
    "Celery Root",
    "Jerusalem Artichoke",
    "Yam",
    "Lotus Root"
]

top_300_foods = [
    "Pizza",
    "Burger",
    "Sushi",
    "Pasta",
    "Taco",
    "Noodle",
    "Rice",
    "Steak",
    "Salad",
    "Sandwich",
    "Soup",
    "Fried Chicken",
    "Curry",
    "Dumplings",
    "BBQ",
    "Ramen",
    "Fish and Chips",
    "Pancake",
    "Waffle",
    "Burrito",
    "Fajitas",
    "Pad Thai",
    "Fried Rice",
    "Lasagna",
    "Tandoori Chicken",
    "Hamburger",
    "Hot Dog",
    "French Fries",
    "Spaghetti",
    "Tiramisu",
    "Sashimi",
    "Bagel",
    "Croissant",
    "Dim Sum",
    "Pho",
    "Miso Soup",
    "Gyoza",
    "Shrimp",
    "Calamari",
    "Clam Chowder",
    "Crab",
    "Lobster",
    "Oyster",
    "Scallop",
    "Shrimp Scampi",
    "Sushi Roll",
    "Tuna",
    "Ceviche",
    "Guacamole",
    "Nachos",
    "Quesadilla",
    "Chili Con Carne",
    "Enchiladas",
    "Tamales",
    "Empanadas",
    "Fried Plantains",
    "Paella",
    "Gazpacho",
    "Tortilla Española",
    "Hummus",
    "Falafel",
    "Shawarma",
    "Kebab",
    "Goulash",
    "Pierogi",
    "Stuffed Cabbage Rolls",
    "Borscht",
    "Pelmeni",
    "Baba Ganoush",
    "Tabbouleh",
    "Baklava",
    "Dolma",
    "Kofta",
    "Kunafa",
    "Lahmacun",
    "Moussaka",
    "Shakshuka",
    "Spanakopita",
    "Tzatziki",
    "Varenyky",
    "Biryani",
    "Butter Chicken",
    "Chaat",
    "Dal",
    "Korma",
    "Rogan Josh",
    "Saag Paneer",
    "Samosa",
    "Tandoori Roti",
    "Vada Pav",
    "Banh Mi",
    "Bun Cha",
    "Com Tam",
    "Goat Curry",
    "Pho Bo",
    "Bak Kut Teh",
    "Char Kway Teow",
    "Hainanese Chicken Rice",
    "Laksa",
    "Nasi Goreng",
    "Satay",
    "Teh Tarik",
    "Adobo",
    "Balut",
    "Lechon",
    "Pancit",
    "Sinigang",
    "Tapsilog",
    "Tom Yum",
    "Bakso",
    "Gado-Gado",
    "Nasi Campur",
    "Rendang",
    "Sate",
    "Soto",
    "Bolognese Sauce",
    "Carbonara",
    "Marinara Sauce",
    "Pesto",
    "Alfredo Sauce",
    "Béchamel Sauce",
    "Baba Au Rhum",
    "Bouillabaisse",
    "Coq Au Vin",
    "Crepes",
    "Croque Madame",
    "Escargot",
    "Foie Gras",
    "Quiche Lorraine",
    "Ratatouille",
    "Tarte Tatin",
    "Beef Wellington",
    "Bubble and Squeak",
    "Cornish Pasty",
    "Full English Breakfast",
    "Haggis",
    "Ploughman's Lunch",
    "Scotch Egg",
    "Shepherd's Pie",
    "Toad in the Hole",
    "Trifle",
    "Welsh Rarebit",
    "Blini",
    "Borscht",
    "Caviar",
    "Pelmeni",
    "Pirozhki",
    "Shashlik",
    "Stroganoff",
    "Vodka",
    "Bourekas",
    "Cholent",
    "Falafel",
    "Hummus",
    "Kugel",
    "Latkes",
    "Matzo Ball Soup",
    "Pastrami",
    "Reuben Sandwich",
    "Rugelach",
    "Shakshuka",
    "Shawarma",
    "Baguette",
    "Bouillabaisse",
    "Cassoulet",
    "Coq Au Vin",
    "Croissant",
    "Duck Confit",
    "Escargot",
    "Foie Gras",
    "Gratin Dauphinois",
    "Macarons",
    "Quiche Lorraine",
    "Ratatouille",
    "Soufflé",
    "Tarte Tatin",
    "Boeuf Bourguignon",
    "Bouillabaisse",
    "Cassoulet",
    "Crepes",
    "Croissant",
    "Duck Confit",
    "Escargot",
    "Foie Gras",
    "Gratin Dauphinois",
    "Macarons",
    "Quiche Lorraine",
    "Ratatouille",
    "Soufflé",
    "Tarte Tatin",
    "Baklava",
    "Dolma",
    "Kofta",
    "Kunafa",
    "Lahmacun",
    "Moussaka",
    "Shakshuka",
    "Spanakopita",
    "Tzatziki",
    "Varenyky",
    "Baguette",
    "Bouillabaisse",
    "Cassoulet",
    "Coq Au Vin",
    "Croissant",
    "Duck Confit",
    "Escargot",
    "Foie Gras",
    "Gratin Dauphinois",
    "Macarons",
    "Quiche Lorraine",
    "Ratatouille",
    "Soufflé",
    "Tarte Tatin",
    "Beef Wellington",
    "Bubble and Squeak",
    "Cornish Pasty",
    "Full English Breakfast",
    "Haggis",
    "Ploughman's Lunch",
    "Scotch Egg",
    "Shepherd's Pie",
    "Toad in the Hole",
    "Trifle",
    "Welsh Rarebit",
    "Baguette",
    "Bouillabaisse",
    "Cassoulet",
    "Coq Au Vin",
    "Croissant",
    "Duck Confit",
    "Escargot",
    "Foie Gras",
    "Gratin Dauphinois",
    "Macarons",
    "Quiche Lorraine",
    "Ratatouille",
    "Soufflé",
    "Tarte Tatin",
    "Baba Au Rhum",
    "Bouillabaisse",
    "Coq Au Vin",
    "Crepes",
    "Croque Madame",
    "Escargot",
    "Foie Gras",
    "Quiche Lorraine",
    "Ratatouille",
    "Tarte Tatin",
    "Beef Wellington",
    "Bubble and Squeak",
    "Cornish Pasty",
    "Full English Breakfast",
    "Haggis",
    "Ploughman's Lunch",
    "Scotch Egg",
    "Shepherd's Pie",
    "Toad in the Hole",
    "Trifle",
    "Welsh Rarebit",
    "Baguette",
    "Bouillabaisse",
    "Cassoulet",
    "Coq Au Vin",
    "Croissant",
    "Duck Confit",
    "Escargot",
    "Foie Gras",
    "Gratin Dauphinois",
    "Macarons",
    "Quiche Lorraine",
    "Ratatouille",
    "Soufflé",
    "Tarte Tatin",
    "Beef Wellington",
    "Bubble and Squeak",
    "Cornish Pasty",
    "Full English Breakfast",
    "Haggis",
    "Ploughman's Lunch",
    "Scotch Egg",
    "Shepherd's Pie",
    "Toad in the Hole",
    "Trifle",
    "Welsh Rarebit",
    "Blini",
    "Borscht",
    "Caviar",
    "Pelmeni",
    "Pirozhki",
    "Shashlik",
    "Stroganoff",
    "Vodka",
    "Bourekas",
    "Cholent",
    "Falafel",
    "Hummus",
    "Kugel",
    "Latkes",
    "Matzo Ball Soup",
    "Pastrami",
    "Reuben Sandwich",
    "Rugelach",
    "Shakshuka",
    "Shawarma"
]


if __name__ == "__main__":

    topics = sorted(set(NEWS_TOPICS)) + sorted(set(top_100_companies)) + sorted(set(top_100_cars)) + sorted(set(
        top_100_animals)) + sorted(set(top_100_fruits)) + sorted(set(top_100_vegetables)) + sorted(set(top_300_foods))

    topics = [topic.lower()+"\n" for topic in topics]

    # topics += [s+"\n" for s in sorted(set(top_100_stocks))]

    with open('topics.txt', 'w') as f:
        f.writelines(topics)
        # for w in set(NEWS_TOPICS):
        #     f.write(f'"{w}",')
